### ISSUE TITLE
Limitation of sub-form based custom renderer on DataTable column

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#1144]
1. Json List does not render even if a Json Entity property is referencing a Json list/list in general: https://function-adminportal-test.shesha.dev/dynamic/Shesha.Enterprise/jsonEntity-render
2. ChildTagEntityGroup: Item is undefined
3. The size of the `Entity Picker` and `autocomplete `when rendered is smaller than what is expected. Both components stretches when they have data
4. File List attach a ghost property on submission
5. The components are squashed and there's no space. You have to use columns to create space in between
6.  Formatting when the sub calls entity properties: https://function-adminportal-test.shesha.dev/dynamic/TestModule/formatTable-test
7. Notes added within an existing entity, can't be retrieved
8. The subform values does not change to white when a row is selected as it does for the data column upon selection
9. It should be possible to specify a minimum row height (moved from #1129 )

**Item number 3**
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/06a8985a-2dcc-4f14-a087-06eaa77ad640)

**Item number 5**
The form rendered on the table does not have space in between components. Example:
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/06a8985a-2dcc-4f14-a087-06eaa77ad640)
Example of the required spacing in between components
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/de527692-a72f-4766-83a9-6c43cfef1717)

**Item number 6**
When formatting is applied to the nested entities, the formatting does not reflect in the table. For example, when DateField format is applied to the 'dateOfBirth' property of the person entity through entity configurations, the 'dateOfBirth' value does not display according to the applied date formatting in the Entity Configurations. The same issue occurs with the 'address.latitude' property

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/eb10c9db-e43c-474c-8f51-ae7cd7bc95ec)
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/b0fffb69-f928-43a3-99ad-d2cfad5eac9b)

Example of where the nesting entities formatting within the table works properly: https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/Schools-Table
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/a72225c0-970b-4609-ba90-75f79cded177)

**Item number 8**
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/3299cd62-93da-4232-a68d-4517efb5ed1d)

**Comment by hlayisanimazuze** [comment]
Related Item
- #678

**Comment by AlexStepantsov** [comment]
All fixed/implemented except

**6. Formatting when the sub calls entity properties: https://function-adminportal-test.shesha.dev/dynamic/TestModule/formatTable-test**

Formatting is configured on subform components (in the form designer) and works

**8. The subform values does not change to white when a row is selected as it does for the data column upon selection**


It is quite difficult to set the color to change to white, since the subform is displayed, and not just the text value. The form has its own styles and can use specific styles for each component. Additionally, the color of the highlighted row may conflict with other colored components on the subform, such as the StatusTag.

I think we can move this problem into a separate task, since first it is necessary to explore possible solutions (this is more of a question for UI design). For example, do not change the background to the selected row color for a Form Cell to avoid color conflicts

**Comment by hlayisanimazuze** [comment]
Moved item 8 to backlog: https://github.com/shesha-io/shesha-framework/issues/1278
