### ISSUE TITLE
Horizontal menu component

### ISSUE THREAD

**Issue by ihouvet** [shesha-io/shesha-framework#1157]
**Is your feature request related to a problem? Please describe.**
There is a need to be able to support web applications which are publicly facing rather than simply admin portals, As is common on many public portals, the main navigation is placed horizontally below the header. In contrast the current main menu for the Admin Portal is rendered vertically with fairly fixed styling.

**Describe the solution you'd like**
- A new horizontal menu component should be provided that provides sufficient flexibility in terms of styling so as to be suitable for a publicly facing web-site
- Configuration of the menu structure should be similar to any other menu or button group in the admin portal
- To provide flexibility in terms of look and feel we should perhaps support the following custom styling options:
  - CustomStyling
  - CustomStylingOnHover
  - CustomStylingSelected
- Additionally, a range of configuration options should be provided that allow fairly custom look & feel to be achieved (see examples below).
- There should be a clearly documented set of CSS class names that could be overridden at the CSS level

**Some screenshots of common publicly facing navigation menu structures**
The solution should ideally allow the following types of styling to be supported
![image](https://github.com/shesha-io/shesha-framework/assets/21078025/788a4b94-b2ef-4c98-a003-fb285634e98a)
![image](https://github.com/shesha-io/shesha-framework/assets/21078025/040a4936-02ed-48f5-8ccd-e36d9511faa1)
![image](https://github.com/shesha-io/shesha-framework/assets/21078025/b6b05100-9b93-42a2-91e9-41b055321f59)
![image](https://github.com/shesha-io/shesha-framework/assets/21078025/fb7b70e9-29c7-41d2-8d0b-723980b0ef67)
![image](https://github.com/shesha-io/shesha-framework/assets/21078025/fedac8a2-4d66-4f71-ac05-bbb26d669ff5)
![image](https://github.com/shesha-io/shesha-framework/assets/21078025/06c0a9d8-1917-45a2-b8df-6d4a0a377921)
![image](https://github.com/shesha-io/shesha-framework/assets/21078025/2f97b8d1-cc59-426b-af9f-f27e9fc8c99f)

**Comment by hlayisanimazuze** [comment]
Hi @Lukeybooi, with the current implementation, I'm unable to test this item because the requirements are not complete

**Comment by Tshepiso-R** [comment]
Hey @Lukeybooi, Hey 
It’s very difficult to use the custom style to meet the criteria. We need to focus on implementing the remaining requirements.

**Comment by Lukeybooi** [comment]
Hi @Tshepiso-R I've added a color picker to change the menu item and selected menu. This should meet your criteria.

**Comment by Tshepiso-R** [comment]
@Lukeybooi 

1. There is still a need for custom styling properties for onHover and onSelect. This should be a code styling editor that allows a user to add CSS styling.
2. The "Selected Item Background" and "Selected Item Color" properties should be renamed to "Hover Background Color" and "Hover Item Color," respectively, as these properties currently work when you hover.
3. Add "Selected Item Background Color" and "Selected Item Color" properties.
4. Currently, the "Selected Item Background Color" and "Selected Item Color" properties only apply to grouped menu items. This implementation should also be extended to menu items.

**Comment by Tshepiso-R** [comment]
@Lukeybooi as per our discussion, please see the pointer below:

1. **Scroll Overflow shows a line underneath when selected.**
   - When scroll overflow is selected, a line appears underneath/ above the menu items depending on the browser you are using.
   - Expected Behaviour:  No line should appear underneath when scroll overflow is selected by default.

2. **Scroll icons need improvement.**
   - The scroll icons currently have a background color that should be removed.

3. **Inconsistent Hover Item color transitioning.**
   - The hover effect on individual items shows a noticeable transition, but when applied to a menu group, the color changes instantly.

4. **Active color does not work for the Active group.**
   - The color for active items is not being applied to the active group.

5. **Custom Styling not applied for hover and active states.**
   - Custom styling is not functioning as expected for both hover and active items.

## Expected Results
- No line should appear underneath when scroll overflow is selected.
- Scroll icons should have a clean appearance without background color.
- Hover color transitions should be consistent across individual items and menu groups.
- Active color should be correctly applied to the active group.
- Custom styling should be effective for both hover and active states.

## Environment
- *[Mention the environment details, e.g., Browser, Operating System, Device type, etc.]*

## Attachments
- *[Attach the image or any other relevant files]*
