### ISSUE TITLE
Properties not displaying when returning the entity type using JS on the components Autocomplete and Entity Picker

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#1390]
**Description**
Upon setting the entity type through JavaScript, users expect to be able to select display properties and properties for entity filtering seamlessly. However, the system fails to recognize the entity type set via JavaScript, resulting in the absence of available properties for selection. This issue affects both the Entity Picker and Autocomplete components

**To Reproduce**
1. Go to 'https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/twenty-three-details?id=9e58861b-2b22-48e9-a5ab-05fddd8cfe13'
3. Utilize JavaScript to dynamically set the entity type, such as return "Shesha.Core.Address". Attempt to select a display property for the entity type.
4. Try to select a property for entity filtering.

**Actual behavior**
When attempting to select a display property or a property for entity filtering after setting the entity type using JavaScript, no data is displayed. Despite configuring the entity type through JavaScript, the system fails to populate the available properties for display or filtering.

**Expected behavior:**
After setting the entity type using JavaScript, users should be able to select display properties and properties for entity filtering as usual. The system should recognize the entity type and provide a list of available properties for selection, allowing users to proceed with configuring the form without any issues.

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/2e279a96-f803-4297-88c6-1de24afd7d0c)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/c991c254-6773-4304-a922-4c6dd4956377)

**Comment by Tshepiso-R** [comment]
Hey @nthangeniphumudzo, the issue persists. After returning the Entity Type "Boxfusion.SheshaFunctionalTests.Domain.Bank" using JS the Display Properties and the properties on the query builder are still empty upon clicking.  See the screenshot below
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/5c64ac13-7349-476f-ab7e-9691af2cdc03)

**Comment by AlexStepantsov** [comment]
hi @Tshepiso-R @hlayisanimazuze @nthangeniphumudzo 

This is definitely not a problem, but incorrect requirements.
 
A property configured via a JS does not have a specific value and can change while working with the form. Because of this, it is impossible to determine a specific value at a specific point in time.
 
For example, if EntityType has a JS like this - 
```
return data.type === 1
    ? 'Shesha.Person'
    : data.type === 2
        ? 'Shesha.Member'
        : 'MyProject.Superman';
```

Properties from which class should be shown in the drop-down list?

In the designer mode we can't know which class will be used at a specific point in time

If such a feature is really needed and is not just a random test experiment, then real use cases and specific requirements should be described.
For example, "Display Property" should also become computable via JS...
 
The current Issue is meaningless, since explicitly specifying the entity type as text via JS is equivalent to selecting a value from a drop-down list and has no meaning. And if the JS contains a complex condition, then it is impossible to determine the entity type in the designer and PropertyAutocomplete will not work anyway.
 
It is possible to implement something like this, but it will definitely add additional load to the system, as it will require additional calculations of the model. This is why specific use cases are needed so that the implementation will optimal and generally makes sense.

**Comment by Tshepiso-R** [comment]
Hey @AlexStepantsov, thanks for the clarity. I will close the issue.
