### ISSUE TITLE
Forgot Password and Register in Dialogue boxes instead of a new screen

### ISSUE THREAD

**Issue by AlexanderSlavchovUX** [shesha-io/shesha-framework#1449]
Is it possible to create a dialogue box that pops up over the login screen similar to the example in the High Fidelity design?

Here is the Figma design
![Sign Up Example](https://github.com/shesha-io/shesha-framework/assets/153498650/a4ec912b-b3e6-47ea-8e69-4f0df414515a)

Our current implementation navigates us to a entirely new screen, it feels smoother and more natural for a dialogue box to pop up over the login screen since the fields for both Forgot Password and Register are quite few.  Once a user has signed up/reset password they are back at the login screen. 

Here is the current implementation: 
![forgotpass](https://github.com/shesha-io/shesha-framework/assets/153498650/d4db6d97-4b6f-487b-9f45-17b13f70c866)

@Lukeybooi  advised that this was done due to this being the standard on Admin Portal, I'm making the ticket so we can discuss this with @ihouvet and then we can make a decision after.

**Comment by Lukeybooi** [comment]
Hi @AlexanderSlavchovUX I've updated the UI for Forgot Password. The Registration should be configurable.

**Comment by hlayisanimazuze** [comment]
Hi @Lukeybooi , the requirement was  to create a dialogue box that pops up over the login screen instead of navigating to a page. I know there's a card to allow the login to be configurable, won't that be handled with that implementation?

As it stands, the forgot password still navigates to a page instead of a dialog
![image](https://github.com/shesha-io/shesha-framework/assets/151041759/1c3c72fa-fef2-4096-a0bb-e55765225816)

**Comment by hlayisanimazuze** [comment]
This item will be addressed after the configurable item is resolved
