### ISSUE TITLE
DataTableContext refresh in script ignores applied filters

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2294]
Description

1. In Step 1, a book is created, and its bookId is stored in the pageContext.
2. Upon proceeding to Step 2, a dialog prompts the user to select a school. The configurations are done on after next within step 1
3. After the school is selected, a new subject is created, and the table in Step 2 is filtered using the bookId from Step 1.
4. The table is refreshed afterward. However, the getAll endpoint, which is triggered via a script, does not pass the filter.

**Steps to reproduce the behavior:**
1. Go to 'https://functional-adminportal-test.azurewebsites.net/dynamic/TestModule/book-refresh'
5. Click on 'Add'
6. Open your nextwork/console
7. Enter all the details in step 1 then click on Next button
8. From the pop-up, select a school
9. Afterwards, check the table endpoint to see if the filter was applied and confirm if the console shows the ID used to filter with on the dataTable
10. Actual results: The subject getEndpoint does not pass the filter a

**Expected behavior**
Upon refreshing the dataTableContext 2, the filter should be applied

**Comment by AlexStepantsov** [comment]
Hi @hlayisanimazuze @ktsapo 

Let's start with this - https://www.mendix.com/blog/asynchronous-vs-synchronous-programming/

All actions on the button in Shesha are asynchronous. This is evident from the description of the methods:
<img width="647" alt="image" src="https://github.com/user-attachments/assets/c354a024-9e03-4fdb-977e-9f48a0792650">

Including you return a Promise object, which is executed asynchronously. This means that the system will not wait for the execution to complete, but will perform the following actions immediately.

Displaying a Modal Dialog is also asynchronous, otherwise, when displaying a Modal Dialog, the browser's response to any other events (including sending and receiving data) would be blocked.

If we return to the form configuration, then in the case where you configured the sequence as follows

1. Entered data at Step 1
2. Clicked the Next button, the BeforeNext script is executed, in which a request to create a book is sent. You return a Promise object, which is a response as onSuccess. The execution of the Promise is asynchronous, so the next action is started immediately.
3. The next action is AfterNext. There you call the Modal Dialog. Opening the Modal Dialog is asynchronous, so the next action is started immediately.
4. The next action is to display Step 2, in which a request is immediately sent to receive data for the table with the filter that is currently available. But, given that all actions were asynchronous, the request sent in point 2 (creating a book) may not yet return a response. Or it could have returned a response and the filter seems to be there, but... look what happens next
5. For the table in Step 2, we need a Book-School (Subject) link, which is created after closing the Modal Dialog. That is, even if there is a BookId, the request for the table will not return the correct data, since it does not exist yet.

Okay, our first request cannot return the correct data, what next...

6. In the Modal Dialog, we select a school, click the custom Next button and run the script to create the Book-School (Subject) link. This action is also ASYNCHRONOUS! And just like in point 2 - you return a Promise object, which is a response as onSuccess. The execution of the Promise is asynchronous, so the next action is started immediately.
7. And the next action is closing the window and another one is refreshing the table.
8. But the request to create the Book-School (Subject) connection has only just been sent, it is also ASYNCHRONOUS, the response has not been received and the object has not yet been created!
9. Therefore, the request for the table will also work incorrectly...

Okay, what needs to be done...

You just need to set the filter value at the end of all asynchronous actions that return data.

In the case of your form - onSuccess when creating the Book-School (Subject) connection. Since in this part of the code we have access to BookId only through PageContext, we simply add a new field
<img width="627" alt="image" src="https://github.com/user-attachments/assets/05c09c90-2f25-422d-b818-b169a653f1ed">

which we then use in the filter
<img width="644" alt="image" src="https://github.com/user-attachments/assets/988b3f84-747d-4a71-bbac-36c70b085dcd">

In addition, there is no need to manually call the script to refresh the table. The table will refresh as soon as the filter value changes.

But I personally don't like that several unnecessary queries are executed for the table, which in principle cannot return correct data. It would be good to get rid of them
<img width="309" alt="image" src="https://github.com/user-attachments/assets/458076a6-9c4a-436a-9b0a-e5b48432c697">

At the moment we don't have the ability to perform a query to get data for a table by condition.
But we can add a condition to the Hidden field so that the table is hidden until a value is set for the filter.
![image](https://github.com/user-attachments/assets/82f3ee34-d9c7-44d7-94cc-7b04de421752)

This way the table will be refreshed only once, when all operations for normal filtering are completed.
![image](https://github.com/user-attachments/assets/913a8bcf-5e21-43c8-b21f-4c1322267e42)

We have only 4 requests:
1. Create Book
2. Request list of schools
3. Create Item
4. Request data for Step 2 table
