### ISSUE TITLE
Error `Could not create an instance of type Shesha.OPT.Dto.ISendPinInput` occurs when sending an OTP

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2310]
When attempting to send an OTP via Swagger, the payload requires only the sendType parameter. However, executing the request as expected results in an error. Even after expanding the payload to include all required details, the error persists.

Is the required parameters not supposed to be part of the payload? See below from old project
![otp sendPin](https://github.com/user-attachments/assets/2a16729d-ee1f-453f-b2c2-a3f48f6cc72e)

**Steps to reproduce the behavior:**
1. Go to 'swagger' and search for 'OTP' service
2. Click on 'SendPin' endpoint
3. Provide the sendType and execute/expand to include sendTo then execute
4. See attached error
![image - 2024-10-21T140134 424](https://github.com/user-attachments/assets/2c1a48ad-590e-4780-8567-e83efc826ce5)

**Expected behavior**
The endpoint should succeed and send the Pin via the mode selected

ND: After fixing, please double check the other OTP endpoints such as ResendPin, VerifyPin etc since I can't due to this

**Comment by MarshallRJ** [comment]
@IvanIlyichev,  @hlayisanimazuze. I found the changing the input methods in the OtpAppService  to use the implemented classes instead of the Interface resulted in the error no longer displaying. Eg:

` public async Task<ISendPinResponse> SendPinAsync(SendPinInput input)` instead of ` public async Task<ISendPinResponse> SendPinAsync(ISendPinInput input)`

So I'd would guess its related to using the interface objects in the service methods.

 Another potential issue is the Get OTP Method ` public async Task<IOtpDto> GetAsync(Guid operationId)` can be accessed without Auth. In my understanding this is a potential security risk as it would allow the pin the read without having to receive it via email or sms. I think this method should be secured so that you at least have to have a valid token to do the get.

**Comment by hlayisanimazuze** [comment]
@OmolemoBlessingLethuloe, please check the comment provided by @MarshallRJ

**Comment by IvanIlyichev** [comment]
@OmolemoBlessingLethuloe let me check it on my side first

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check

**Comment by hlayisanimazuze** [comment]
Part of release 40
