### ISSUE TITLE
Side menu becomes misaligned and visually distorted

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2419]
The side menu becomes misaligned and visually distorted after certain actions or page loads. The styling appears inconsistent, making the menu look unorganized or difficult to use.

**Steps to reproduce the behavior:**
1. URL: https://pd-supplychainmanagement-adminportal-qa.azurewebsites.net/
2. Use private tab
3. After logging in, navigate to workflow and click my items
4. Click 'create new' and select the second item (all should still give you the same results)
5. Scroll down entirely to the bottom of the page
6. Afterwards, instead of using the back arrow, use your mouse pad to go back to the table view
7. From the table, refresh the page
8. Actual Results: The side menu is misaligned and visually distorted

**Expected behavior**
The side menu should remain properly aligned and maintain consistent styling across all pages

![image - 2024-11-21T064135 646](https://github.com/user-attachments/assets/f6fcd692-0dfd-42bc-a35e-91e2629b936d)

![image - 2024-11-21T063814 859](https://github.com/user-attachments/assets/365301f3-739d-44c6-99d8-5a4eccef1fdb)

**Comment by hlayisanimazuze** [comment]
This will be required on releases/0.39

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze.  The reason of this bug is deep inside [ant-design/cssinjs](https://github.com/ant-design/cssinjs) library, looks like it calculates cache by a wrong way in some very specific cases. I've applied latest changes (including [this one](https://github.com/shesha-io/shesha-framework/issues/1936)) to the supplychainmanagement admin portal, you can check it on [test site](https://pd-supplychainmanagement-adminportal-test.azurewebsites.net/). It works as expected now

**Comment by hlayisanimazuze** [comment]
I’ve received positive feedback from the supply chain developer. Since the update, they haven’t encountered the issue. I will close this item for now and will reopen it if it reoccurs
