### ISSUE TITLE
Formatting for Nested Entities in Referenced Table

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#587]
**Description**
 The applied formatting on nested entity configurations is not being correctly displayed on the referenced table.

**Scenario 1:**
-  If you have a subject referencing a book, if you had applied formatting on the book price, the format does not apply on the table. 
      - Link: https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/School-Details?id=cb62d813-f798-44e6-8006-023b619b7c5a. 
- _See the quickview pop-up, it does not have the formatting applied to the price while the book table does show the formatting_
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/e8f777d9-00ba-45eb-a7c3-62703395bbd7)
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/b6297ad0-63b8-4dea-a311-433f5b41b000)

**Scenario 2:**
-  You have a bridging entity: https://pd-playground-adminportal-test.shesha.dev/shesha/forms-designer/?id=39dbb8b9-ed41-4290-bdc8-bc6bf1f3fbe3 
   - You have a projectPerson that references the project. When you tap on the entity e.g. project.accumulatedCost, the formatting applied on the accumatedCost it does not apply when the data is being displayed on the projectPerson table

**Acceptable Criteria**
The applied formatting on nested entity configurations is not being correctly displayed on the referenced table.

**Comment by hlayisanimazuze** [comment]
Hi @Lukeybooi , seems like you only apply your implementation on 'number' property and on quickview. Check my second scenario below the screenshots, the change should also be applied when I tap on the entity e,g,` book.price` instead of using a quickview. The change is not only being required for number formatting, but every property where you apply formatting on the Entity Configuration such as `Date/Datefield`

Example of Datefield: https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/changeslatest-details?id=b7f0594e-9a6b-478d-bf35-e71962070507. Hover over the member quickview and compare the formatting applied on `membershipEndDate` with the `membershipEndDate `applied on the details view

Example of tapping onto the entity: https://function-adminportal-test.shesha.dev/dynamic/Boxfusion.SheshaFunctionalTests.Common/entityref-table. Check` lat-long` columns and compare the formatting applied on the `address `quickview

**Comment by Lukeybooi** [comment]
Hi @AlexStepantsov I've noticed that the issue is on the properties passed from `useMetadata` on the DatePicker component. The incorrect property is being passed and the fallback format is being used. Can you kindly assist? 

![image](https://github.com/shesha-io/shesha-framework/assets/33176583/67920b88-e5f4-4138-9049-449160fde399)

**Comment by hlayisanimazuze** [comment]
extension of this item: https://github.com/shesha-io/shesha-framework/issues/978
