### ISSUE TITLE
Make the header bar a configurable form

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#601]
#### Story:
As a user, I want the ability to customize the header bar of the application by configuring its elements. This customization should include the flexibility to move elements to different positions and update the logo easily.

#### Acceptance Criteria:

- As a user configuring the header bar, I should be able to move items to different positions within the header.
- The configuration interface should provide an intuitive way to update the logo in the header.

![image](https://github.com/shesha-io/shesha-framework/assets/151129946/143d9426-cf90-47b1-9b98-958a899c1e35)

**Comment by hlayisanimazuze** [comment]
**Breakdown of the requirements discussed during the sprint planning**

Standard Header Form:
- Create a standard form named "header."
- This form should be pre-configured with existing components.

Login and Other Icons:
-  Login and livemode a latest should be grouped in two separate components
- These components should be distinct and separate.

Editing Header:
- When editing the header, it should open the standard form configuration.
- Pre-load the standard components in the form.

Visibility of Header Components:
- Ensure that all components related to the header are visible on the builder widgets only when the header form is in designer mode. Otherwise, the components should be hidden and only accessible when the header form itself is in designer mode.

**Comment by hlayisanimazuze** [comment]
Related Item
#1565
