### ISSUE TITLE
Allow configurator to easily specify placeholder content when a DataTable is empty

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#700]
### Description:
When a data table does not have any rows, we currently just display an empty table. It is often useful to be able to provide additional guidance to the user.

### Acceptance Criteria:
1. Add the following configuration properties on the DataTable component to customise what is displayed to users when the table is empty / no rows:
   a. Add an 'Empty Table' configuration section with the following properties: 
      -  Icon - Icon to display when no rows are availble (should support no icon)
      - Primary text - default to 'No Data'
      -  Secondary text - default to 'No data is available for this table'
2. Similar functionality should be added to the DataList component

**Comment by hlayisanimazuze** [comment]
Hi 

Please check the properties titles and compare with the above requirements. Rename the properties according to the requirements such as:

- Icon instead of Icon Picker
- Primary text instead of No Data Primary Text
- Secondary text instead of No Data secondary Text

On dataList, the default text for secomdary Text is not exposed from the configurations. Be consistent 

![image](https://github.com/shesha-io/shesha-framework/assets/151041759/cad39877-68ed-4df2-a2c8-adfa5aaa0211)
