### ISSUE TITLE
Reference list not naved after drag-and-drop, resulting in missing radio buttons

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#890]
**Description:**
When dragging and dropping a property that utilizes radio buttons from the data panel, the associated reference list property is not saved. Consequently, upon saving the form and rendering it, the radio buttons do not appear. Upon investigation in designer mode, it is observed that the reference list property is empty, contributing to the absence of radio buttons.

**Steps to Reproduce:**
1. Go to "https://function-adminportal-test.shesha.dev/dynamic/Shesha/test-pre-release"
2. Click the Add button
3. Navigate to the form designer
1. Drag and drop a property with radio buttons from the data panel onto the form e.g. gender.
2. Configure the reference list property 
4. Save the form and render it
5. Observe that the radio buttons do not display.
6. Navigate to designer mode
7. Actual Results: Notice that the reference list property is empty again.

**Expected Behavior:**
When you drag and drop the reference list property from the data section, the reference list property should be prepopulated with the associated reference list name.

Form Configuration
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/e0dc669a-b261-461c-941b-462c9f00edf0)

Rendered Form:
![image](https://github.com/shesha-io/shesha-framework/assets/151129946/9a092e45-b0fb-4099-91d7-0ee0f849edf6)

**Comment by IvanIlyichev** [comment]
Hi @hlayisanimazuze. It's fixed, please check

**Comment by hlayisanimazuze** [comment]
Hi @IvanIlyichev, This is partially resolved. When you drag and drop a reference list property from the data section, the property is already bound to the reference list name. However, the issue arises when rendering the form; the reference list items are not showing. When navigating to configurations, the reference list field is empty, and the previously bound reference list is removed. Refer to the attached video: https://boxfusionint-my.sharepoint.com/:v:/g/personal/hlayisani_mazuze_boxfusion_io/ERjl6TqRbqpGrB9Au7emy4QB3vnN89sKSbGRag_yESQPIg?e=4IaBrZ


Current behavior: When you configure the reference list name and render the form, now the reference list item shows


**Expected Results:** When you drag and drop a reference list property from the data section, since the property comes bound to the reference list name, when you render the form, it should show the reference list items.

Links:
- https://function-adminportal-test.shesha.dev/shesha/forms-designer?id=9de95ba9-1517-45c9-8a00-cb43294305d6
- https://function-adminportal-test.shesha.dev/dynamic/TestModule/reference-draganddroptable
